### ISSUE TITLE
preview window not compatible with NerdTree

### ISSUE THREAD

**Issue by wyyqyl** [dyng/ctrlsf.vim#43]
The width of the `NerdTree` window will be minimized after pressing `p` in the `CtrlSF` window, and the `NerdTree` window will almost be invisible. The width of the `NerdTree` window will keep minimized even after closing the `CtrlSF` window.

The **left** window is the `NerdTree` window
![image](https://cloud.githubusercontent.com/assets/787659/8098902/7ca5690a-1028-11e5-871c-8b24bb13af5d.png)

**Comment by dyng** [comment]
Have confirmed this issue. I need to think about how to corporate windows with other plugin's.

Thank you for your bug reporting.

**Comment by dyng** [comment]
Fixed this issue in 0e839. But I need some more test.

If you like, you can checkout `v1.1` branch and test it, please let me know if you find any other issue.

**Comment by dyng** [comment]
Merged in #48 .

**Comment by wyyqyl** [comment]
Sorry for the late reply. I find some bug after trying it out.
1. with nerdtree window open, if I press p for the preview window, the nerdtree window will be minimized
2. with nerdtree window open, if I open preview window for at least 3 times, and press q to close `CtrlSF` window, the nerdtree window is minimized. But if I preview for less than 3 times, it works well.

**Comment by dyng** [comment]
> with nerdtree window open, if I press p for the preview window, the nerdtree window will be minimized

This behavior is by design. Actually CtrlSF can't keep width of NerdTree intact, but fall back to restore it after closing itself.

> with nerdtree window open, if I open preview window for at least 3 times, and press q to close CtrlSF window, the nerdtree window is minimized. But if I preview for less than 3 times, it works well.

I can't reproduce this issue. Maybe it is an issue has something to do with other plugins or settings. Can you test it again with all other plugins disabled, and upload a detailed steps to reproduce.

#### Another way to address this issue:
**Place CtrlSF window at bottom**, by this command

```vim
let g:ctrlsf_position = 'bottom'
```

**Comment by wyyqyl** [comment]
With all plugins disabled except for ctrlsf and nerdtree, the problem remains.
![terminal](https://cloud.githubusercontent.com/assets/787659/8511682/172f50b8-2356-11e5-9472-140780dff375.gif)

**Comment by dyng** [comment]
@wyyqyl 

I have located the bug and fixed it in #50. Please update to the latest version.

If you still have problem with latest version, feel free to reopen this issue.

Thank you for your detailed bug report, it helps me much. :)

**Comment by wyyqyl** [comment]
Great job, it works well now, thanks a lot!
